#!/usr/bin/env bash

snakefile=$(katuali_datafile Snakefile)
snakefile=$(katuali_datafile config.yaml)


log_dir=logs
config_dir=configs

silent=false
args="--restart-times 3"
config_opts=""
cluster_opt=""
cluster_parm=""
sge_opt="--latency-wait 300 --cluster-sync"
sge_parm="$(which qsub) -V -cwd -l {params.sge} -sync yes -o $log_dir -j y" 

for i in "$@"; 
do
    case "${1-}" in
        -s)
            snakefile="${2-}"
            shift 2
            ;;
        --snakefile)
            snakefile="${2-}"
            shift 2
            ;;
        --configfile)
            config="${2-}"
            shift 2
            ;;
        --cluster*)
            cluster_opt="${1-}"
            cluster_parm="\"${2-}\""
            shift 2
            ;;
        --sge)
            cluster_opt=$sge_opt
            cluster_parm="\"$sge_parm\""
            shift 1
            ;;
        --config)
            shift 1
            while true; do
                if [[ ${1-} == *"="* ]]; then 
                    config_opts="$config_opts ${1-}";
                    shift 1;
                else
                    break
                fi
            done
            ;;
        -h)
            args="$args help"
            shift 1
            ;;
        --help)
            args="$args help"
            shift 1
            ;;
        --silent)
            silent=true
            shift 1
            ;;
        *)
            args="$args ${1-}"
            shift 1
            ;;
    esac
done


mkdir -p $config_dir $log_dir

t=$(date --rfc-3339=seconds | sed 's/ /_/')
configout="${config_dir}/katuali_${t}.yaml"
log="${log_dir}/katuali_${t}.log"

process_katuali_config $config $configout $config_opts

cmd="snakemake -s ${snakefile} --configfile $configout $args $cluster_opt $cluster_parm"

if $silent; then 
    echo $cmd | bash &> $log
else
    echo "Running $cmd"
    echo "Config saved to $configout"
    echo "Log saved to $log" 
    echo $cmd | bash 2>&1 | tee $log
fi
